### ISSUE TITLE
jenkins-slave kubectl not found

### ISSUE THREAD

**Issue by kindule** [carlossg/kubernetes-jenkins#4]
Hi!

I use jenkinsci/jnlp-slave docker for our kubernetes ci system, and found the error below. So we need install kubectl in jnlp-slave by ourself?

```
$ kubectl config --kubeconfig=/home/jenkins/workspace/Sphinx/.kube8336248897384256363config set-cluster k8s --server=http://10.10.80.86:8080 --insecure-skip-tls-verify=true
FATAL: Cannot run program "kubectl": error=2, No such file or directory
java.io.IOException: Cannot run program "kubectl": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at hudson.Proc$LocalProc.<init>(Proc.java:244)
    at hudson.Proc$LocalProc.<init>(Proc.java:216)
    at hudson.Launcher$LocalLauncher.launch(Launcher.java:816)
    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1149)
    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1114)
    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
    at hudson.remoting.Request$2.run(Request.java:326)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at hudson.remoting.Engine$1$1.run(Engine.java:69)
    at java.lang.Thread.run(Thread.java:745)
    at ......remote call to 17d3ba2d45ab(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
    at hudson.remoting.Channel.call(Channel.java:778)
    at hudson.Launcher$RemoteLauncher.launch(Launcher.java:929)
    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
    at hudson.Launcher$ProcStarter.join(Launcher.java:389)
    at org.csanchez.jenkins.plugins.kubernetes.KubectlBuildWrapper.setUp(KubectlBuildWrapper.java:64)
    at jenkins.tasks.SimpleBuildWrapper.setUp(SimpleBuildWrapper.java:146)
    at hudson.model.Build$BuildExecution.doRun(Build.java:156)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)
```

**Comment by carlossg** [comment]
if you want to use any tool in the slave you need to install it

**Comment by k82cn** [comment]
@kindule , kubectl is not necessary; this plugin will create a Pod for you.

**Comment by chandanagcp** [comment]
i want to configure Kubecctl env as  I want to build and publish the images to GCR, can anyone help on this
